-- THIS FILE IS FOR INTELLISENSE PURPOSES ONLY
-- USAGE: require("constants")

-- SCANCODES
SCANCODE_UNKNOWN = 0
SCANCODE_A = 4
SCANCODE_B = 5
SCANCODE_C = 6
SCANCODE_D = 7
SCANCODE_E = 8
SCANCODE_F = 9
SCANCODE_G = 10
SCANCODE_H = 11
SCANCODE_I = 12
SCANCODE_J = 13
SCANCODE_K = 14
SCANCODE_L = 15
SCANCODE_M = 16
SCANCODE_N = 17
SCANCODE_O = 18
SCANCODE_P = 19
SCANCODE_Q = 20
SCANCODE_R = 21
SCANCODE_S = 22
SCANCODE_T = 23
SCANCODE_U = 24
SCANCODE_V = 25
SCANCODE_W = 26
SCANCODE_X = 27
SCANCODE_Y = 28
SCANCODE_Z = 29
SCANCODE_1 = 30
SCANCODE_2 = 31
SCANCODE_3 = 32
SCANCODE_4 = 33
SCANCODE_5 = 34
SCANCODE_6 = 35
SCANCODE_7 = 36
SCANCODE_8 = 37
SCANCODE_9 = 38
SCANCODE_0 = 39
SCANCODE_RETURN = 40
SCANCODE_ESCAPE = 41
SCANCODE_BACKSPACE = 42
SCANCODE_TAB = 43
SCANCODE_SPACE = 44
SCANCODE_MINUS = 45
SCANCODE_EQUALS = 46
SCANCODE_LEFTBRACKET = 47
SCANCODE_RIGHTBRACKET = 48
SCANCODE_BACKSLASH = 49
SCANCODE_NONUSHASH = 50
SCANCODE_SEMICOLON = 51
SCANCODE_APOSTROPHE = 52
SCANCODE_GRAVE = 53
SCANCODE_COMMA = 54
SCANCODE_PERIOD = 55
SCANCODE_SLASH = 56
SCANCODE_CAPSLOCK = 57
SCANCODE_F1 = 58
SCANCODE_F2 = 59
SCANCODE_F3 = 60
SCANCODE_F4 = 61
SCANCODE_F5 = 62
SCANCODE_F6 = 63
SCANCODE_F7 = 64
SCANCODE_F8 = 65
SCANCODE_F9 = 66
SCANCODE_F10 = 67
SCANCODE_F11 = 68
SCANCODE_F12 = 69
SCANCODE_PRINTSCREEN = 70
SCANCODE_SCROLLLOCK = 71
SCANCODE_PAUSE = 72
SCANCODE_INSERT = 73
SCANCODE_HOME = 74
SCANCODE_PAGEUP = 75
SCANCODE_DELETE = 76
SCANCODE_END = 77
SCANCODE_PAGEDOWN = 78
SCANCODE_RIGHT = 79
SCANCODE_LEFT = 80
SCANCODE_DOWN = 81
SCANCODE_UP = 82
SCANCODE_NUMLOCKCLEAR = 83
SCANCODE_KP_DIVIDE = 84
SCANCODE_KP_MULTIPLY = 85
SCANCODE_KP_MINUS = 86
SCANCODE_KP_PLUS = 87
SCANCODE_KP_ENTER = 88
SCANCODE_KP_1 = 89
SCANCODE_KP_2 = 90
SCANCODE_KP_3 = 91
SCANCODE_KP_4 = 92
SCANCODE_KP_5 = 93
SCANCODE_KP_6 = 94
SCANCODE_KP_7 = 95
SCANCODE_KP_8 = 96
SCANCODE_KP_9 = 97
SCANCODE_KP_0 = 98
SCANCODE_KP_PERIOD = 99
SCANCODE_NONUSBACKSLASH = 100
SCANCODE_APPLICATION = 101
SCANCODE_POWER = 102
SCANCODE_KP_EQUALS = 103
SCANCODE_F13 = 104
SCANCODE_F14 = 105
SCANCODE_F15 = 106
SCANCODE_F16 = 107
SCANCODE_F17 = 108
SCANCODE_F18 = 109
SCANCODE_F19 = 110
SCANCODE_F20 = 111
SCANCODE_F21 = 112
SCANCODE_F22 = 113
SCANCODE_F23 = 114
SCANCODE_F24 = 115
SCANCODE_EXECUTE = 116
SCANCODE_HELP = 117
SCANCODE_MENU = 118
SCANCODE_SELECT = 119
SCANCODE_STOP = 120
SCANCODE_AGAIN = 121
SCANCODE_UNDO = 122
SCANCODE_CUT = 123
SCANCODE_COPY = 124
SCANCODE_PASTE = 125
SCANCODE_FIND = 126
SCANCODE_MUTE = 127
SCANCODE_VOLUMEUP = 128
SCANCODE_VOLUMEDOWN = 129
SCANCODE_KP_COMMA = 133
SCANCODE_KP_EQUALSAS400 = 134
SCANCODE_INTERNATIONAL1 = 135
SCANCODE_INTERNATIONAL2 = 136
SCANCODE_INTERNATIONAL3 = 137
SCANCODE_INTERNATIONAL4 = 138
SCANCODE_INTERNATIONAL5 = 139
SCANCODE_INTERNATIONAL6 = 140
SCANCODE_INTERNATIONAL7 = 141
SCANCODE_INTERNATIONAL8 = 142
SCANCODE_INTERNATIONAL9 = 143
SCANCODE_LANG1 = 144
SCANCODE_LANG2 = 145
SCANCODE_LANG3 = 146
SCANCODE_LANG4 = 147
SCANCODE_LANG5 = 148
SCANCODE_LANG6 = 149
SCANCODE_LANG7 = 150
SCANCODE_LANG8 = 151
SCANCODE_LANG9 = 152
SCANCODE_ALTERASE = 153
SCANCODE_SYSREQ = 154
SCANCODE_CANCEL = 155
SCANCODE_CLEAR = 156
SCANCODE_PRIOR = 157
SCANCODE_RETURN2 = 158
SCANCODE_SEPARATOR = 159
SCANCODE_OUT = 160
SCANCODE_OPER = 161
SCANCODE_CLEARAGAIN = 162
SCANCODE_CRSEL = 163
SCANCODE_EXSEL = 164
SCANCODE_KP_00 = 176
SCANCODE_KP_000 = 177
SCANCODE_THOUSANDSSEPARATOR = 178
SCANCODE_DECIMALSEPARATOR = 179
SCANCODE_CURRENCYUNIT = 180
SCANCODE_CURRENCYSUBUNIT = 181
SCANCODE_KP_LEFTPAREN = 182
SCANCODE_KP_RIGHTPAREN = 183
SCANCODE_KP_LEFTBRACE = 184
SCANCODE_KP_RIGHTBRACE = 185
SCANCODE_KP_TAB = 186
SCANCODE_KP_BACKSPACE = 187
SCANCODE_KP_A = 188
SCANCODE_KP_B = 189
SCANCODE_KP_C = 190
SCANCODE_KP_D = 191
SCANCODE_KP_E = 192
SCANCODE_KP_F = 193
SCANCODE_KP_XOR = 194
SCANCODE_KP_POWER = 195
SCANCODE_KP_PERCENT = 196
SCANCODE_KP_LESS = 197
SCANCODE_KP_GREATER = 198
SCANCODE_KP_AMPERSAND = 199
SCANCODE_KP_DBLAMPERSAND = 200
SCANCODE_KP_VERTICALBAR = 201
SCANCODE_KP_DBLVERTICALBAR = 202
SCANCODE_KP_COLON = 203
SCANCODE_KP_HASH = 204
SCANCODE_KP_SPACE = 205
SCANCODE_KP_AT = 206
SCANCODE_KP_EXCLAM = 207
SCANCODE_KP_MEMSTORE = 208
SCANCODE_KP_MEMRECALL = 209
SCANCODE_KP_MEMCLEAR = 210
SCANCODE_KP_MEMADD = 211
SCANCODE_KP_MEMSUBTRACT = 212
SCANCODE_KP_MEMMULTIPLY = 213
SCANCODE_KP_MEMDIVIDE = 214
SCANCODE_KP_PLUSMINUS = 215
SCANCODE_KP_CLEAR = 216
SCANCODE_KP_CLEARENTRY = 217
SCANCODE_KP_BINARY = 218
SCANCODE_KP_OCTAL = 219
SCANCODE_KP_DECIMAL = 220
SCANCODE_KP_HEXADECIMAL = 221
SCANCODE_LCTRL = 224
SCANCODE_LSHIFT = 225
SCANCODE_LALT = 226
SCANCODE_LGUI = 227
SCANCODE_RCTRL = 228
SCANCODE_RSHIFT = 229
SCANCODE_RALT = 230
SCANCODE_RGUI = 231
SCANCODE_MODE = 257
SCANCODE_SLEEP = 258
SCANCODE_WAKE = 259
SCANCODE_CHANNEL_INCREMENT = 260
SCANCODE_CHANNEL_DECREMENT = 261
SCANCODE_MEDIA_PLAY = 262
SCANCODE_MEDIA_PAUSE = 263
SCANCODE_MEDIA_RECORD = 264
SCANCODE_MEDIA_FAST_FORWARD = 265
SCANCODE_MEDIA_REWIND = 266
SCANCODE_MEDIA_NEXT_TRACK = 267
SCANCODE_MEDIA_PREVIOUS_TRACK = 268
SCANCODE_MEDIA_STOP = 269
SCANCODE_MEDIA_EJECT = 270
SCANCODE_MEDIA_PLAY_PAUSE = 271
SCANCODE_MEDIA_SELECT = 272
SCANCODE_AC_NEW = 273
SCANCODE_AC_OPEN = 274
SCANCODE_AC_CLOSE = 275
SCANCODE_AC_EXIT = 276
SCANCODE_AC_SAVE = 277
SCANCODE_AC_PRINT = 278
SCANCODE_AC_PROPERTIES = 279
SCANCODE_AC_SEARCH = 280
SCANCODE_AC_HOME = 281
SCANCODE_AC_BACK = 282
SCANCODE_AC_FORWARD = 283
SCANCODE_AC_STOP = 284
SCANCODE_AC_REFRESH = 285
SCANCODE_AC_BOOKMARKS = 286
SCANCODE_SOFTLEFT = 287
SCANCODE_SOFTRIGHT = 288
SCANCODE_CALL = 289
SCANCODE_ENDCALL = 290
SCANCODE_RESERVED = 400
SCANCODE_COUNT = 512

-- EVENTS
EVENT_FIRST = 0
EVENT_QUIT = 256
EVENT_TERMINATING = 257
EVENT_LOW_MEMORY = 258
EVENT_WILL_ENTER_BACKGROUND = 259
EVENT_DID_ENTER_BACKGROUND = 260
EVENT_WILL_ENTER_FOREGROUND = 261
EVENT_DID_ENTER_FOREGROUND = 262
EVENT_LOCALE_CHANGED = 263
EVENT_SYSTEM_THEME_CHANGED = 264
EVENT_DISPLAY_ORIENTATION = 337
EVENT_DISPLAY_ADDED = 338
EVENT_DISPLAY_REMOVED = 339
EVENT_DISPLAY_MOVED = 340
EVENT_DISPLAY_DESKTOP_MODE_CHANGED = 341
EVENT_DISPLAY_CURRENT_MODE_CHANGED = 342
EVENT_DISPLAY_CONTENT_SCALE_CHANGED = 343
EVENT_DISPLAY_FIRST = 337
EVENT_DISPLAY_LAST = 343
EVENT_WINDOW_SHOWN = 514
EVENT_WINDOW_HIDDEN = 515
EVENT_WINDOW_EXPOSED = 516
EVENT_WINDOW_MOVED = 517
EVENT_WINDOW_RESIZED = 518
EVENT_WINDOW_PIXEL_SIZE_CHANGED = 519
EVENT_WINDOW_METAL_VIEW_RESIZED = 520
EVENT_WINDOW_MINIMIZED = 521
EVENT_WINDOW_MAXIMIZED = 522
EVENT_WINDOW_RESTORED = 523
EVENT_WINDOW_MOUSE_ENTER = 524
EVENT_WINDOW_MOUSE_LEAVE = 525
EVENT_WINDOW_FOCUS_GAINED = 526
EVENT_WINDOW_FOCUS_LOST = 527
EVENT_WINDOW_CLOSE_REQUESTED = 528
EVENT_WINDOW_HIT_TEST = 529
EVENT_WINDOW_ICCPROF_CHANGED = 530
EVENT_WINDOW_DISPLAY_CHANGED = 531
EVENT_WINDOW_DISPLAY_SCALE_CHANGED = 532
EVENT_WINDOW_SAFE_AREA_CHANGED = 533
EVENT_WINDOW_OCCLUDED = 534
EVENT_WINDOW_ENTER_FULLSCREEN = 535
EVENT_WINDOW_LEAVE_FULLSCREEN = 536
EVENT_WINDOW_DESTROYED = 537
EVENT_WINDOW_HDR_STATE_CHANGED = 538
EVENT_WINDOW_FIRST = 514
EVENT_WINDOW_LAST = 538
EVENT_KEY_DOWN = 768
EVENT_KEY_UP = 769
EVENT_TEXT_EDITING = 770
EVENT_TEXT_INPUT = 771
EVENT_KEYMAP_CHANGED = 772
EVENT_KEYBOARD_ADDED = 773
EVENT_KEYBOARD_REMOVED = 774
EVENT_TEXT_EDITING_CANDIDATES = 775
EVENT_MOUSE_MOTION = 1024
EVENT_MOUSE_BUTTON_DOWN = 1025
EVENT_MOUSE_BUTTON_UP = 1026
EVENT_MOUSE_WHEEL = 1027
EVENT_MOUSE_ADDED = 1028
EVENT_MOUSE_REMOVED = 1029
EVENT_JOYSTICK_AXIS_MOTION = 1536
EVENT_JOYSTICK_BALL_MOTION = 1537
EVENT_JOYSTICK_HAT_MOTION = 1538
EVENT_JOYSTICK_BUTTON_DOWN = 1539
EVENT_JOYSTICK_BUTTON_UP = 1540
EVENT_JOYSTICK_ADDED = 1541
EVENT_JOYSTICK_REMOVED = 1542
EVENT_JOYSTICK_BATTERY_UPDATED = 1543
EVENT_JOYSTICK_UPDATE_COMPLETE = 1544
EVENT_GAMEPAD_AXIS_MOTION = 1616
EVENT_GAMEPAD_BUTTON_DOWN = 1617
EVENT_GAMEPAD_BUTTON_UP = 1618
EVENT_GAMEPAD_ADDED = 1619
EVENT_GAMEPAD_REMOVED = 1620
EVENT_GAMEPAD_REMAPPED = 1621
EVENT_GAMEPAD_TOUCHPAD_DOWN = 1622
EVENT_GAMEPAD_TOUCHPAD_MOTION = 1623
EVENT_GAMEPAD_TOUCHPAD_UP = 1624
EVENT_GAMEPAD_SENSOR_UPDATE = 1625
EVENT_GAMEPAD_UPDATE_COMPLETE = 1626
EVENT_GAMEPAD_STEAM_HANDLE_UPDATED = 1627
EVENT_FINGER_DOWN = 1792
EVENT_FINGER_UP = 1793
EVENT_FINGER_MOTION = 1794
EVENT_FINGER_CANCELED = 1795
EVENT_CLIPBOARD_UPDATE = 2304
EVENT_DROP_FILE = 4096
EVENT_DROP_TEXT = 4097
EVENT_DROP_BEGIN = 4098
EVENT_DROP_COMPLETE = 4099
EVENT_DROP_POSITION = 4100
EVENT_AUDIO_DEVICE_ADDED = 4352
EVENT_AUDIO_DEVICE_REMOVED = 4353
EVENT_AUDIO_DEVICE_FORMAT_CHANGED = 4354
EVENT_SENSOR_UPDATE = 4608
EVENT_PEN_PROXIMITY_IN = 4864
EVENT_PEN_PROXIMITY_OUT = 4865
EVENT_PEN_DOWN = 4866
EVENT_PEN_UP = 4867
EVENT_PEN_BUTTON_DOWN = 4868
EVENT_PEN_BUTTON_UP = 4869
EVENT_PEN_MOTION = 4870
EVENT_PEN_AXIS = 4871
EVENT_CAMERA_DEVICE_ADDED = 5120
EVENT_CAMERA_DEVICE_REMOVED = 5121
EVENT_CAMERA_DEVICE_APPROVED = 5122
EVENT_CAMERA_DEVICE_DENIED = 5123
EVENT_RENDER_TARGETS_RESET = 8192
EVENT_RENDER_DEVICE_RESET = 8193
EVENT_RENDER_DEVICE_LOST = 8194
EVENT_PRIVATE0 = 16384
EVENT_PRIVATE1 = 16385
EVENT_PRIVATE2 = 16386
EVENT_PRIVATE3 = 16387
EVENT_POLL_SENTINEL = 32512
EVENT_USER = 32768
EVENT_LAST = 65535
EVENT_ENUM_PADDING = 2147483647

---@meta _

---SDL Mouse Button Constants
---@enum MouseButton
BUTTON = {
    LEFT = 1,
    MIDDLE = 2,
    RIGHT = 3,
    X1 = 4,
    X2 = 5,
}

---SDL Mouse Button Masks (for checking button state)
---@class MouseButtonMask
BUTTON_MASK = {
    LEFT = 0x01,    -- 1 << 0
    MIDDLE = 0x02,  -- 1 << 1
    RIGHT = 0x04,   -- 1 << 2
    X1 = 0x08,      -- 1 << 3
    X2 = 0x10,      -- 1 << 4
}

---Vector 2D
---@class vec2
---@field x number
---@field y number

---Vector 3D
---@class vec3
---@field x number
---@field y number
---@field z number

---Vector 4D / Color
---@class vec4
---@field x number
---@field y number
---@field z number
---@field w number
---@field r number Color red channel
---@field g number Color green channel
---@field b number Color blue channel
---@field a number Color alpha channel

---2D Transform component
---@class Transform2D
---@field position vec2
---@field scale vec2
---@field rotation number Rotation in radians

---3D Transform component
---@class Transform3D
---@field position vec3
---@field rotation vec3 Euler angles in radians
---@field scale vec3

---2D Shape component
---@class Shape2D
---@field color vec4
---@field filled boolean

---2D Label/Text component
---@class Label2D
---@field text string
---@field color vec4
---@field font_name string
---@field font_size number

---3D Camera component
---@class Camera3D
---@field position vec3
---@field yaw number Yaw angle in degrees
---@field pitch number Pitch angle in degrees
---@field fov number Field of view in degrees
---@field speed number Movement speed
---@field view_distance number Far plane distance
---@field move_forward fun(self: Camera3D, delta_time: number) Move camera forward
---@field move_backward fun(self: Camera3D, delta_time: number) Move camera backward
---@field move_left fun(self: Camera3D, delta_time: number) Move camera left
---@field move_right fun(self: Camera3D, delta_time: number) Move camera right
---@field look_at fun(self: Camera3D, xoffset: number, yoffset: number, sensitivity?: number) Rotate camera
---@field zoom fun(self: Camera3D, yoffset: number) Zoom camera
---@field get_view_matrix fun(self: Camera3D): mat4 Get view matrix
---@field get_projection_matrix fun(self: Camera3D, width: integer, height: integer): mat4 Get projection matrix

---4x4 Matrix
---@class mat4


---@class Cube
---@field size number Size of the cube
---@field color vec4 Color of the cube


---Game entity with components
---@class Entity
---@field id integer Unique entity ID
---@field name string Entity name
---@field is_valid boolean Whether entity is still valid
---@field transform2d? Transform2D 2D transform component
---@field transform? Transform3D 3D transform component
---@field shape2d? Shape2D 2D shape component
---@field label2d? Label2D 2D label component
---@field camera? Camera3D 3D camera component
---@field cube? Cube 3D cube component
---@field has_component fun(self: Entity, component_name: string): boolean Check if entity has component
---@field add_component fun(self: Entity, component_name: string): boolean Add component to entity
---@field get_component fun(self: Entity, component_name: string): any Get component from entity
---@field remove_component fun(self: Entity, component_name: string): boolean Remove component from entity

---Viewport configuration
---@class Viewport
---@field width integer Viewport width in pixels
---@field height integer Viewport height in pixels
---@field scale number Viewport scale factor

---Window configuration
---@class Window
---@field width integer Window width in pixels
---@field height integer Window height in pixels
---@field dpi_scale number DPI scaling factor

---Renderer device configuration
---@class RendererDevice
---@field backend string Rendering backend name
---@field texture_filtering string Texture filtering mode

---Engine configuration
---@class EngineConfig
---@field get_viewport fun(self: EngineConfig): Viewport Get viewport configuration
---@field get_window fun(self: EngineConfig): Window Get window configuration
---@field get_renderer_device fun(self: EngineConfig): RendererDevice Get renderer device configuration

---Main engine class
---@class Engine
---@field get_config fun(self: Engine): EngineConfig Get engine configuration

---Global engine singleton
---@type Engine

---Input handling
---@class Input
---@field get_mouse_position fun(): vec2 Get current mouse position
---@field is_key_pressed fun(key_code: integer): boolean Check if key is pressed

---@type Input

---Scene management
---@class Scene
---@field change_scene fun(scene_name: string) Change to a different scene
---@field get_entities_count fun(): integer Get total number of entities

---@type Scene

---Current entity (available in entity scripts)
---@type Entity