"""Type stubs for the native `golias` module.
"""

from typing import Any

class Vector3:
    x: float
    y: float
    z: float
    def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 0.0) -> None: ...

class Vector2:
    x: float
    y: float
    def __init__(self, x: float = 0.0, y: float = 0.0) -> None: ...

def deg_to_rad(degrees: float) -> float: ...

class Transform:
    def rotate_local(self, axis: Vector3, radians: float) -> None: ...
    def get_position(self) -> Vector3: ...
    def set_position(self, position: Vector3) -> None: ...
    def get_world_position(self) -> Vector3: ...
    def set_world_position(self, position: Vector3) -> None: ...
    def get_forward(self) -> Vector3: ...

class GameObject:
    def get_name(self) -> str: ...
    def get_transform(self) -> Transform: ...
    def is_active(self) -> bool: ...
    def set_active(self, active: bool) -> None: ...

class Time:
    @staticmethod
    def get_delta_time() -> float: ...
    @staticmethod
    def get_elapsed_time() -> float: ...

class Input:
    @staticmethod
    def is_key_pressed(key: str) -> bool: ...
    @staticmethod
    def get_mouse_position() -> Vector2: ...

class PythonBehavior:
    """Base class for golias scripts. `self` proxies the owning GameObject."""

    def start(self) -> None: ...
    def update(self, delta_time: float) -> None: ...
    def on_enable(self) -> None: ...
    def on_disable(self) -> None: ...
    def on_destroy(self) -> None: ...

    @property
    def transform(self) -> Transform: ...
    def get_name(self) -> str: ...
    def set_active(self, active: bool) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
